# Oscars.com MariaDB Data Uploader

Data Collection, Integration and Preprocessing

Hochschule Luzern, 2024

Master's in Applied Information and Data Science

Dominik Bacher Suarez

The following code upload the stage3 datafram to a MariaDB databse

In [1]:
import mariadb
import pandas as pd
import sqlalchemy

## Make connection

In [2]:
# Make the connection to MariaDB
user="cip_user"
password="cip_pw"
host="localhost" #"127.0.0.1", 
port="3306"
database="OSCARS_STUDENTA"

engine = sqlalchemy.create_engine(f"mariadb+mariadbconnector://{user}:{password}@{host}:{port}/{database}")

## Upload Data to MariaDB

In [3]:
# Open the original CSV files
df_stage3 = pd.read_csv("../Data/Bacher_Dominik_studentA_stage3.csv")

In [4]:
df_stage3.head(3)

,Movie Title,Oscar Ceremony Year,Cast Involved,Actor in a Leading Role,Actor in a Supporting Role,Actress in a Leading Role,Actress in a Supporting Role,Animated Feature Film,Animated Short Film,Art Direction,...,Sound,Sound Editing,Sound Mixing,Visual Effects,Writing (Adapted Screenplay),Writing (Original Screenplay),Won_Oscars,Oscars_Won,Total_Oscars_Awarded,Percentage of Wins
0,12 Years a Slave,2014,"Chiwetel Ejiofor, Michael Fassbender, Lupita N...",Nominated,Nominated,NaN,Winner,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Winner,NaN,True,3,23,13.04
1,127 Hours,2011,"James Franco, Jon Harris, A.R. Rahman, Christi...",Nominated,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Nominated,NaN,False,0,22,0.00
2,13 Hours: The Secret Soldiers of Benghazi,2017,"Gary Summers, Jeffrey J. Haboush and Mac Ruth",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Nominated,NaN,NaN,NaN,False,0,23,0.00

In [5]:
# Create the table in MariaDB from original CSV
df_stage3.to_sql(
    'Bacher_Dominik_studentA_stage3', 
    con=engine, 
    index=False, 
    if_exists='replace'
)

864

## Load from MariaDB

In [10]:
df_stage3_mariadb = pd.read_sql_table('Bacher_Dominik_studentA_stage3', con=engine)

print(F"Loaded {len(df_stage3_mariadb)} rows from the table 'Bacher_Dominik_studentA_stage3' from MariaDB")
print("Here is a sample:")
df_stage3_mariadb

Loaded 864 rows from the table 'Bacher_Dominik_studentA_stage3' from MariaDB
Here is a sample:

,Movie Title,Oscar Ceremony Year,Cast Involved,Actor in a Leading Role,Actor in a Supporting Role,Actress in a Leading Role,Actress in a Supporting Role,Animated Feature Film,Animated Short Film,Art Direction,...,Sound,Sound Editing,Sound Mixing,Visual Effects,Writing (Adapted Screenplay),Writing (Original Screenplay),Won_Oscars,Oscars_Won,Total_Oscars_Awarded,Percentage of Wins
0,12 Years a Slave,2014,"Chiwetel Ejiofor, Michael Fassbender, Lupita N...",Nominated,Nominated,None,Winner,None,None,None,...,None,None,None,None,Winner,None,1,3,23,13.04
1,127 Hours,2011,"James Franco, Jon Harris, A.R. Rahman, Christi...",Nominated,None,None,None,None,None,None,...,None,None,None,None,Nominated,None,0,0,22,0.00
2,13 Hours: The Secret Soldiers of Benghazi,2017,"Gary Summers, Jeffrey J. Haboush and Mac Ruth",None,None,None,None,None,None,None,...,None,None,Nominated,None,None,None,0,0,23,0.00
3,13th,2017,"Ava DuVernay, Spencer Averick and Howard Barish",None,None,None,None,None,None,None,...,None,None,None,None,None,None,0,0,23,0.00
4,1917,2020,"Roger Deakins, Sam Mendes, Naomi Donne, Trista...",None,None,None,None,None,None,None,...,None,Nominated,Winner,Winner,None,Nominated,1,3,24,12.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,Writing with Fire,2022,Rintu Thomas and Sushmit Ghosh,None,None,None,None,None,None,None,...,None,None,None,None,None,None,0,0,22,0.00
860,X-Men: Days of Future Past,2015,"Richard Stammers, Lou Pecora, Tim Crosbie and ...",None,None,None,None,None,None,None,...,None,None,None,Nominated,None,None,0,0,23,0.00
861,Yes-People,2021,GÃ­sli Darri HalldÃ³rsson and Arnar Gunnarsson,None,None,None,None,None,None,None,...,None,None,None,None,None,None,0,0,21,0.00
862,Zero Dark Thirty,2013,"Jessica Chastain, Dylan Tichenor and William G...",None,None,Nominated,None,None,None,None,...,None,Nominated,None,None,None,Nominated,0,0,22,0.00
863,Zootopia,2017,"Byron Howard, Rich Moore and Clark Spencer",None,None,None,None,Winner,None,None,...,None,None,None,None,None,None,1,1,23,4.35

In [11]:
# Inspect the tables inside the database
inspector = sqlalchemy.inspect(engine)

tables = inspector.get_table_names()
print("List of tables in the database 'OSCARS_STUDENTA':")
for table in tables:
    print(table)

List of tables in the database 'OSCARS_STUDENTA':
Bacher_Dominik_studentA_stage3

In [ ]:
# Code to drop tables:
drop_statement = sqlalchemy.text("DROP TABLE IF EXISTS table3;")

with engine.connect() as connection:
    connection.execute(drop_statement)
    connection.commit()